# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.univ.in:
  peer0.annauniv.univ.in:
  peer1.annauniv.univ.in:
  peer0.bit.univ.in:
  peer1.bit.univ.in:

networks:
  univnetwork:

services:

  orderer.univ.in:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.univ.in
    container_name: orderer.univ.in
    networks:
      - univnetwork

  peer0.annauniv.univ.in:
    container_name: peer0.annauniv.univ.in
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.annauniv.univ.in
    networks:
      - univnetwork

  peer1.annauniv.univ.in:
    container_name: peer1.annauniv.univ.in
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.annauniv.univ.in
    networks:
      - univnetwork

  peer0.bit.univ.in:
    container_name: peer0.bit.univ.in
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.bit.univ.in
    networks:
      - univnetwork

  peer1.bit.univ.in:
    container_name: peer1.bit.univ.in
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.bit.univ.in
    networks:
      - univnetwork

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      #- CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.annauniv.univ.in:7051
      - CORE_PEER_LOCALMSPID=annaunivMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/annauniv.univ.in/peers/peer0.annauniv.univ.in/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/annauniv.univ.in/peers/peer0.annauniv.univ.in/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/annauniv.univ.in/peers/peer0.annauniv.univ.in/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/annauniv.univ.in/users/Admin@annauniv.univ.in/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    # command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.univ.in
      - peer0.annauniv.univ.in
      - peer1.annauniv.univ.in
      - peer0.bit.univ.in
      - peer1.bit.univ.in
    networks:
      - univnetwork
